sudo: false
language: python

python:
    - "2.7"
    - "pypy"
    - "pypy3"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
    include:
    - python: "3.5"
      env: TOXENV="-e pep8"
install:
    - pip install --upgrade pip setuptools
    - pip install tox-travis
script:
    - tox $TOXENV
